# Generated by Django 2.0 on 2018-01-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('paymethod', models.BigIntegerField(default=0)),
                ('referer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='invertory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expdate', models.DateTimeField(verbose_name='exp date')),
                ('activedate', models.DateTimeField(verbose_name='active date')),
                ('paprice', models.FloatField(default=0)),
                ('soldtime', models.DateTimeField(verbose_name='sold time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbrand', models.CharField(max_length=200)),
                ('pmodel', models.CharField(max_length=200)),
                ('psprice', models.FloatField(default=0)),
                ('pcolor', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='invertory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
