# Generated by Django 2.0 on 2018-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('0', 'male'), ('1', 'female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referer',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='activedate',
            field=models.DateField(verbose_name='active date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expdate',
            field=models.DateField(verbose_name='exp date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='soldtime',
            field=models.DateField(verbose_name='sold time'),
        ),
    ]
